### ISSUE TITLE
Return types on mocked methods cause static analysis failures

### ISSUE THREAD

**Issue by asgrim** [Jan0707/phpstan-prophecy#23]
A method being mocked might be called like:

```php
$this->mockedClass->someMethod()->willReturn(123);
```

Even if `$mockedClass` is annotated correctly, such as:

```
/** @var MyClass|ObjectProphecy */
private $mockedClass;
```

`someMethod()` for example might return an `int`, so you'd get a warning from phpstan like:

```
Cannot call method willReturn() on int. 
```

Not sure if this is even possible to handle really, but thought I'd at least bring it up for discussion! Thanks!

**Comment by asgrim** [comment]
FWIW, as a workaround I have:

```yaml
parameters:
    ignoreErrors:
        - '#Cannot call method (?:willReturn|shouldBeCalledOnce|shouldNotBeCalled|shouldBeCalled|shouldNotHaveBeenCalled)\(\) on .*\.#'
```
